iconchoice = ['⭐️','💧','🍎','🔥','☀️','🍒','🍏','🍕','🍬','🍙','🥠','🍔','🌮','🥗','🎨','🏉','🏀','🐶','🐱','🐭','🐻','🧠','🦇','👑','🐢','🦀','🔭','🍀','🌹','🌻','🌸','🚗','💻','💰','💎','⛓','🗡','💣','🔮','🎈','🔎','♠️','♣️','♥️','♦️','✂️','📚','🧪','⚔️','🛡','🔫','🎲','🎮','🚲','🛸','☕️','🍱','🥚','🌲','🤡','👻','👾','💡','🍄','🐚','🍖','🍜','⚙️','🖍','🧲','🎱','🥔','🧀','☄️','⛄️','🌿','🐍','🖋','🌙','✨','❄️','🌧','🥕','🍨','🍪','🍩','✏️','🏹','🎹','🕹','🛎','📌','📷','💄','🌼','💫','🦴','🌭','🍡','🔩','🧁','🍸','🧰','🔋','🎙','🧶','🎩','💍','🧳','🎓','🎒','🐹','🐝','🦈','🐬','🍁','🌾','🍇','🥞','🥩','🍜','🍦','🥊','🏓','🎬','🎻','💿','🎞','🧯','🛢','🛠','⚖️','🔬','🏮','📋','📰']

persc = [
# unsure if these will do anything
"Normal", # nothing special
"Responsible", # your law-abiding citizen
"Calm", # also very normal
"Modest", # do I need all this
"Practical",

"Friendly", # helps out, does favors
"Peppy", # bursting with energy
"Cheerful", # cheery

"Kind", # it's just gentle, seriously
"Gentle", # friendly but softer
"Good", # tries to do the right thing always

"Quiet", # okay
"Blank", # seemingly emotionless
"Cool", # competent and self-assured
"Cold", # mean
"Mysterious", # secretive

"Annoying", # bothersome, loud
"Dumb", # just dumb

"Weird", # does dumb and random things
"Obsessive", # fixated, intense, disturbing
"Scary", # disquieting

"Clever", # just brains

"Nerdy", # science, books, technology
"Chuuni", # mega geek for animes
"Geeky", # bideogames and internet culture

"Energetic", # spornts but not spornts
"Athletic", # spornts

"Angry", # maybe violent, maybe tsundere
"Tough", # grouchy, strong, maybe violent

"Victim", # pathetic, an easy target
"Shy", # nervous and wilting
"Awkward", # like victim but more pathetic
"Lonely", # hangdog puppydog

"Smug", # smirks, lofty, better-than-you

"Rude", # I just think of miu

"Cute", # uwu. is this a personality
"Childish", # it is a personality

"Refined", # totally just elegant
"Elegant", # fancy pants
"Polite", # same but not fancy pants

"Relaxed", # like slacker but not as bad
"Slacker", # lazy, chill, relaxed
"Lazy", # yeah

"Tired", # tired
"Gloomy", # oh, boo hoo

"Forgetful", # airhead

"Funny", # what's a jokes?
"Prankster", # okay
"Bully", # yep

"Naive", # or innocent

"Oblivious", # huh?

"Popular", # stereotype popular

"Passionate", # what it sounds like
"Serious", # no jokes, intense, focused

"Furry", # why not

]

talentchoice = [

# uh
"Doctor",
"Surgeon",
"Nurse",
"Plastic Surgeon",
"Neurosurgeon",
"Anesthesiologist",

"Mathematician",

"Roboticist",
"Programmer",
"Hacker",
"Cryptographer",

"Zoologist",
"Aquarist",
"Marine Biologist",
"Herpetologist",

"Inventor",
"Philosopher",
"Researcher",

"Geologist",
"Archaeologist",

"Engineer",
"Rocket Scientist",
"Sports Scientist",
"Food Scientist",
"Nanoscientist",

"Meterologist",
"Astronomer",

"Psychiatrist",

"Chemist",
"Pharmacist",
"Pathologist",

"Historian",

"Architect",

# art and performance
"Musician",

"Drummer",
"Pianist",
"Violinist",
"Guitarist",

"Singer",
"Idol",
"Dancer",
"Celebrity",
"Rock Star",
"Pop Star",
"Movie Star",

"Cosplayer",
"Costume Designer",
"Stylist",

"Actor",

"Artist",
"Animator",
"Manga Artist",
"Cartoonist",
"Graphic Designer",
"Painter",
"Sculptor",

"Magician",
"Illusionist",

"Jeweler",

"Model",
"Photographer",
"Cinematographer",
"Movie Director",
"Critic",

# martial
"Forensics Analyst",
"Detective",

"Fighter",
"Soldier",
"Agent",
"Sniper",
"Gunner",
"Mercenary",
"Bounty Hunter",

"Pilot",
"Fighter Pilot",
"Parachuter",

"Hunter",
"Angler",

"Scout",
"Tracker",
"Guide",
"Cartographer",
"Adventurer",
"Courier",

"Bodyguard",
"Guard",

"Jockey",

"Racecar Driver",

"Astronaut",

"Demolitionist",

"Storm Chaser",

"Sailor",

"Firefighter",

# leadership and administrative
"Leader",
"Student President",
"Politician",
"Publicist",

"Manager",

"Secretary",
"Assistant",

"Lawyer",
"Judge",

"Accountant",

"Police Officer",
"Hall Monitor",

# service
"Chef",
"Baker",

"Butcher",

"Sommelier",
"Gourmet",

"Tailor",

"Therapist",

"Teacher",
"Tutor",

"Librarian",

"Janitor",

"Homemaker",
"Butler",
"Maid",

"Gardener",
"Farmer",
"Rancher",

"Candymaker",

"Toymaker",

"Florist",

"Translator",

"Mixologist",

"Lifeguard",

"Mechanic",
"Electrician",
"Plumber",

"Tactician",
"Mortician",
"Taxidermist",

"Animal Tamer",
"Dog Walker",
"Pet Sitter",
"Cat Whisperer",

"Veterinarian",

"Bugcatcher",
"Beekeeper",

# writing and reporting
"Author",

"Poet",

"Journalist",
"Reporter",

"Editor",

# athletic
"Coach",

"Runner",
"Freerunner",

"Gymnast",
"Acrobat",

"Climber",

"Figure Skater",

"Surfer",
"Swimmer",
"Surfer",

"Bodybuilder",
"Powerlifter",

"Kickboxer",
"Wrestler",
"Martial Artist",
"Sumo Wrestler",

"Boxer",
"Cyclist",
"Biker",
"Skater",

"Swordfighter",
"Kendoka",
"Judoka",
"Aikidoka",
"Archer",

"Baseball Player",
"Soccer Player",
"Hockey Player",
"Football Player",
"Tennis Player",
"Golfer",

"Chess Player",

# other 
"Clown",
"Juggler",
"Gangster",
"Robot",
"Knight",
"Ninja",
"Thief",
"Noble",
"Psychic",
"Fortune Teller",
"Disguiser",
"Gambler",

"Hypnotist",
"Ghost Hunter",

"???",
"Good Luck",
"Survivor",

"e-Sports Gamer",
"Gamer",
"Voice Actor",
"Radio Host",

"Influencer",
"Comedian",

]


likes = [
# sound
"Quiet places",
"Loud spaces",
"Absolute silence",
"Noise",
"White noise",
"The sound of static",
"The sound of electricity",
"The sound of gunshots",
"The sounds of battle",
"The sound of screams",
"The sound of whispers",
"The sound of plastic crinkling",
"The sound of people yelling",
"The sound of laughter",
"The sound of rain",
"The sound of cards shuffling",
"The sound of dice rolling",
"The sound of thunder",
"The sound of explosions",
"The sound of water boiling",
"The sound of crying",
"The sound of nails on a chalkboard",
"The sound of smoke alarms",
"The sound of chanting",
"The sound of hail falling on roofs",
"The sound of traffic",
"Imagining what ghosts sound like",
"Piano music",
"Classic music",
"Rock music",
"Jazz music",
"Pop music",
"Game music",
"Violin music",
"Ambulance alarms",
"People singing",
"Arcade sounds",
"Clicking pens",
"Electronic crackling",
"Birdsong",
"Crickets chirping",

# smell
"The smell of fresh coffee",
"The smell just after it rains",
"The smell of blood",
"The smell of fresh-cut grass",
"The smell of fresh-cut onions",
"The smell of fresh flowers",
"The smell of dried flowers",
"The smell of old books",
"The smell of gunsmoke",
"The smell of electrical fires",
"The smell of gasoline",
"The smell of fresh-brewed tea",
"The smell of baking bread",
"The smell of soap",
"The smell of a brand-new car",
"The smell of firewood",
"The smell of smoke",
"The smell of leather",
"The smell of ozone",
"The smell of flowers",
"The smell of swimming pools",
"The smell of incense",
"The smell of peppermint",
"Tomato smell",
"Cigarette smoke",
"Chemical smells",

# social
"Being left alone",
"Meeting new people",
"Learning about people",
"Being around people",
"Talking to people",
"Keeping in touch",

# internet and games activities
"Listening to podcasts",
"Making podcasts",
"Reading fanfiction",
"Writing fanfiction",
"Cosplaying",
"Looking at fanart",
"Drawing fanart",
"Watching streams",
"Everything about retro games",
"Fighting games",
"Everything about videogames",
"Playing videogames",
"Playing strategy games",
"Reading visual novels",
"Playing datesims",
"Virtual reality",
"Browsing forums",
"Browsing the internet",
"Chat programs",
"Using social media",
"Looking at memes",
"Making memes",
"Card games",

# random objects
"Cursed things",
"Blessed things",
"Soft things",
"Hard things",
"Arcade buttons",
"Arcade sticks",
"Lost things",
"Smooth things",
"Rough things",
"Very small things",
"Artificial things",
"Very big things",
"Sparkly things",
"Beautiful things",
"Trendy things",
"Popular things",
"Sharp things",
"Sticky things",
"Unusual things",
"High art",
"Expensive things",
"Old and worn things",
"Colorful things",
"Dirty things",
"Magnifying glasses",
"Fingerprint kits",
"Music vinyls",
"Music records",
"Doorbells",
"Cages",
"Teacups",
"Teapots",
"Kitchen utensils",
"Butter knives",
"Batteries",
"Clean things",
"Monochrome things",
"See-through things",
"Stained glass windows",
"Smelly things",
"Other people's belongings",
"Collectibles",
"Old newspapers",
"Stacks of books",
"Broken lightbulbs",
"Toilets",
"Lockpicks",
"Keys and locks",
"Eyes",
"Glass eyes",
"Teeth",
"Magazines",
"All sorts of manga",
"Old books",
"New books",
"Locked doors",
"Open doors",
"Glasses",
"Cameras",
"Photographs",
"Diaries",
"Journals",
"Sewing needles",
"Paper wrappers",
"Needles",
"Medical needles",
"Medical masks",
"Military surplus",
"Bolts of cloth",
"Brand-new clothes",
"Rocks",
"Fancy shoes",
"Fancy accessories",
"High-tech gadgets",
"Thermometers",
"Stoplights",
"Phones",
"Giant robots",
"Cars",
"Ships",
"Trains",
"Audio equipment",
"Power lines",
"Steam",
"Clocks",
"Computers",
"Wires and cables",
"Electrical components",
"Planets",
"Comets",
"Shooting stars",
"Black holes",
"Dark matter",
"Atoms",
"Sticky notes",
"Flypaper",
"Bottles of glue",
"Nuts and bolts",
"Cooking utensils",
"Antiques",
"Plastic bottles",
"Plastic bags",
"New things",
"Movie cases",
"Game cases",
"Windows",
"Balls of yarn",
"Loose string",
"Piles of blankets",
"Spaceships",
"Piles of pillows",
"Rope",
"Boxes",
"Empty boxes",
"Gold",
"Silver",
"Steel",
"Street lamps",
"Paper lanterns",
"Clothing racks",
"Dice",
"Shells",
"Sheets of paper",
"Grand pianos",
"Vintage guitars",
"All sorts of instruments",
"Broken instruments",
"Unmade beds",
"Tables",
"Stationery",
"Postcards",
"Sinks",
"Rollercoasters",
"Ferris wheels",
"Merry-go-rounds",
"Motorcycles",
"Bathtubs",
"Cards",
"Playing cards",
"Colorful dice",
"Statues",
"Balloons",
"Rubber gloves",
"Wrapping paper",
"Parachutes",
"Lanterns",
"Cups",
"Rusty nails",
"Old electronics",
"Broken things",
"Spoons and forks",
"Toys",
"Machines",
"White gloves",
"Gloves",
"Boots",
"Socks",
"Robots",
"Keys",
"Puzzles",
"Collectible figures",
"Pencil erasers",
"Tangled shoelaces",
"Caution tape",
"Belts",
"Duct tape",
"Hazardous materials",
"Radioactive materials",
"Boardgames",
"Anime figures",
"Milk cartons",
"Grills",
"Fences",
"Gravestones",
"Mirrors",
"Action figures",
"Paper dolls",
"Plastic food",
"Plastic straws",
"Uniforms",
"Baby powder",
"LED lights",
"Hats",
"Ball-jointed dolls",
"Dusty chalk",
"Plush toys",
"Stuffed animals",
"Old coins",
"Precious metals",
"Iron and steel",
"Toolboxes",
"Piles of firewood",
"Scented candles",
"Gems and jewelry",

# weaponry
"All kinds of weaponry",
"Weapons training",
"Knives",
"Bows and arrows",
"Swords",
"Katanas",
"Lances",
"Hammers",
"Maces",
"Guns",
"Explosives",
"Shields",
"Armor",

# gen food and drink
"Trying new foods",
"Unusual foods",
"Gourmet foods",
"Sweet foods",
"Sour foods",
"Salty foods",
"Savory foods",
"Spicy foods",
"Bitter foods",
"Desserts",
"All sorts of candy",

# cookable
"Cheesy pizza",
"Pineapple pizza",

"Burgers",
"French fries",

"Ramen",

"Tofu",
"Natto",

"Hot dogs",
"Chili dogs",

"Plain steamed buns",
"Dumplings",

"Sushi",
"Tuna sashimi",
"Salmon sashimi",
"Sashimi",
"Aged sashimi",

"Jellyfish salad",
"Snails",

"Tempura",

"Stuffed mushrooms",

"Fruit salad",
"Seaweed salad",

"Watery soup",
"Sour soup",
"Apple soup",

"Sandwiches",
"Fruits sandwiches",
"Banh mis",

"Fried rice",
"Rice balls",
"Plain white rice",
"Rice porridge",
"Omurice",

"Plain white bread",
"Buttered toast",
"Burnt toast",
"Avocado toast",

"Buttered popcorn",
"Burnt popcorn",

"Scrambled eggs",
"Fried eggs",
"Soft-boiled eggs",
"Rolled eggs",
"Potato chips",

"Wheels of cheese",
"String cheese",

"Plain spaghetti",
"Konjac noodles",
"Caviar",

"Baked potatoes",
"Mashed potatoes",

"Meat",
"Roast beef",
"Pork chops",
"Deli meat",
"Sausages",
"Horse steak",
"Mystery meats",
"Fried chicken",
"Marrow bones",

"Plain crackers",
"Cheese and crackers",

"Dried beans",
"Dried fish",
"Dried meat",
"Dried fruit",

"Junk food",
"Microwave meals",
"Healthy food",
"Curry",
"Eel rice",
"Boiled fish",

"Pancakes",
"Chocolate",
"White chocolate",
"Milk chocolate",
"Dark chocolate",
"Cakes",
"Candied apples",
"Sugar candy",
"Birthday cakes",
"Pudding",
"Egg tarts",
"Cupcakes",
"Cookies",
"Cinnamon buns",
"Cheesecake",

"Custard buns",
"Bean jam buns",
"Sweet bread",

"Jelly-filled donuts",
"Donuts",
"Ice cream",
"Popsicles",

"Sour candy",
"Fruity candy",
"Chewy candy",
"Fizzy candy",
"Gummy candy",

# extra weird cookables
"Melted ice cream",
"Moldy food",
"Wasabi",
"Pork brains",
"Frozen food",
"Raw eggs",
"Rotten fruit",
]

drink = [
"Fizzy soda",
"Flat soda",
"Soda pop",
"Melon soda",
"Soy milk",
"Milk",
"Herbal tea",
"Lemon tea",
"Sparkling water",
"Mineral water",
"Still water",
"Deep water",
"Rainwater",
"Ice water",
"Tap water",
"Coffee",
"Mocha",
"Cappuccino",
"Fruit tea",
"Sports drinks",
"Protein shakes",
"Milkshakes",
"Ice cream floats",
"Slushies",
"Health drinks",
"Energy drinks",
"Sweet tea",
"Milk tea",
"Green tea",
"Fruits tea",
"Milk",
"Baked milk",
"Sour milk",
"Salt water",
"Fruit juice",
"Apple juice",
"Carrot juice",
"Orange juice",
"Lemonade",
"Chocolate milk",
"Strawberry milk",
"Banana milk",
"Hot cocoa",
"Cold cocoa",
"Mixed drinks",
"Yogurt drink",
"Bone broth",

# not cookable
"Leafy greens",
"Cabbages",
"Wilted vegetables",
"Potatoes",
"Carrots",

"Lemons",
"Green apples",
"Red apples",
"Sour grapes",
"Wormy apples",
"Strawberries",
"Peaches",
"Bananas",
"Plums",
"Sour cherries",

# animals
"All animals",
"Cute animals",
"Cool animals",

"Mice",
"Chickens",
"Cows",
"Sheep",
"Goats",
"Ducks",
"Pigs",
"Horses",

"Dogs",
"Long dogs",
"Terrier dogs",
"Puppies",
"Big cats",
"Fat cats",
"Cats",
"Black cats",
"Cats with fat faces",
"Kittens",
"Parrots that talk",
"Parrots that don't talk",
"Pigeons",
"Hamsters",
"Rats",
"Fish",

"Bats",
"Bears",
"Lions",
"Tigers",
"Elephants",
"Foxes",
"Crows and ravens",
"Birds of prey",
"Snakes",
"Frogs",

"All kinds of bugs",
"Butterflies",
"Wriggly worms",
"Ants",
"Crickets",
"Praying mantises",
"Dragonflies",
"Fireflies",
"Ladybugs",
"Moths",
"Buzzing flies",
"Mosquitoes",
"Snails and slugs",

# colors
"The color red",
"The color orange",
"The color yellow",
"The color green",
"The color blue",
"The color purple",
"The color brown",
"The color gray",
"The color black",
"The color white",
"The color when you close your eyes",

# activities
"Drinking",
"Eating food",
"Playing arcade games",
"Saving money",
"Wasting money",
"Having fun",
"Fashion",
"Dressing up",
"Hand washing",
"Baking",
"Cooking",
"Programming",
"Hacking",
"Mixing drinks",
"Sleeping",
"Napping",
"Sleeping in",
"Sleeping in class",
"Making music",
"Stargazing",
"Hunting",
"Scale modeling",
"Collecting fingerprints",
"Arts and crafts",
"Scrapbooking",
"Petting animals",
"Walking the dog",
"Petting cats",
"Solving mysteries",
"Doing repairs",
"Putting things together",
"Playing boardgames",
"Putting together puzzles",
"Playing puzzle games",
"Playing crosswords",
"Doing brain teasers",
"Researching things",
"Going to aquariums",
"Going to the zoo",
"Going to gardens",
"Going to restaurants",
"Eating with people",
"Sharing food",
"Aquariums",
"Looking at fish",
"Birdwatching",
"Bird hobby",
"Watching TV",
"Arts and crafts",
"Coloring",
"Sketching",
"Robotics",
"Listening to music",
"Listening to the radio",
"Watching movies",
"Daydreaming",
"Worldbuilding",
"Taking walks",
"Jogging",
"Running",
"Fighting",
"Swimming",
"Diving",
"Floating in pools",
"Sunbathing",
"Being by the poolside",
"Being on the beach",
"Going to casinos",
"Taking bets",
"Making bets",
"Going out",
"Staying in",
"Mountain climbing",
"Hiking",
"Playfighting",
"Going fishing",
"Cloud watching",
"Diving",
"Skydiving",
"Going outside",
"Lifting weights",
"Doing cardio",
"Push-ups",
"Drawing",
"Writing",
"Reading books",
"Singing in the shower",
"Going on trips",
"Long walks on the beach",
"Staying in bed",
"Driving around",
"Going fast",
"Taking it slow",
"Dancing",
"Buying things",
"Selling things",
"Making money",
"Going shopping",
"Recycling",
"Cleaning",
"Making tea",
"Drinkig tea",
"Buying presents",
"Giving gifts",
"Opening presents",
"Wrapping presents",
"Gossiping",
"Exercise",
"Treasure hunting",
"Riding in airplanes",
"Flying airplanes",
"Riding on trains",
"Going shopping",
"Sailing",
"Riding on ships",
"Going on cruises",
"Riding bikes",
"Going to parties",
"Hanging out with friends",
"Making costumes",
"Going to costume parties",
"Making jewelry",
"Gardening",
"Chemistry",
"Organizing things",
"Language learning",
"Translation",
"Making snow angels",
"Building snow men",

# nature
"Flowers",
"Nature in general",
"Rivers",
"Getting lost",
"Going on adventures",
"Morning dew",
"When it rains",
"Watching rain fall",
"Going oht in the rain",
"That water is wet",
"When it snows",
"Walking through snow",
"That snow is cold",
"Watching snow fall",
"Going out in the snow",
"Jumping in puddles",
"How hot the sun is",
"When it's sunny",
"When it snows",
"Humid weather",
"Mud puddles",
"Dry heat",
"Swamps",
"Fields",
"Stormy weather",
"Snow storms",
"Thunder and lightning",
"That snow is cold",
"Ice",
"Tornadoes",
"Tsunamis",
"Earthquakes",
"Thunderstorms",
"Floods",
"Clear skies",
"Clouds",
"That clouds move",
"Cloudy days",
"Cold days",
"Hot days",
"Warm days",
"Cool days",
"Windy days",
"Forest fires",
"Fire",
"Being underwater",
"The oceans",
"Mountains",
"Sandy beaches",
"The beach",
"Dark caves",
"Grass",
"The shade under trees",
"Trees",
"Forests",
"Jungles",
"The weather",
"That roses have thorns",
"Sunflowers",
"Potted plants",
"Catnip",
"Poison ivy",
"Climbing ivy",
"Red roses",
"White roses",
"Lilies",
"Deadly nightshade",
"Spider lilies",
"Dandelions",
"Clovers",
"Mushrooms and fungi",
"Rotting vegetation",

# genres
"Action",
"Fairy tales",
"Children's stories",
"Science fiction",
"Drama",
"Fantasy",
"Anime",
"Mecha",
"Romance",
"History",
"Horror",
"Doujinshi",
"Shounen manga",
"Shoujo manga",
"Romance stories",
"Difficult books",
"Light novels",
"Murder mysteries",
"Mystery stories",
"Thrillers",
"Fantasy stories",

# places
"Empty places",
"Hot springs",
"Botanical gardens",
"Places full of things",
"Spas",
"Cramped spaces",
"Spacious rooms",
"Churches",
"Shrines",
"Temples",
"Jails",
"Institutions",
"Offices",
"Staying home",
"Outer space",
"Home",
"Libraries",
"Shopping malls",
"Bathrooms",
"Swimming pools",
"Water parks",
"Laboratories",
"Abandoned buildings",
"Abandoned ruins",
"Liminal spaces",
"Hotels",
"Hospitals",
"Drug stores",
"Pharmacies",
"Haunted houses",
"Campgrounds",
"Playgrounds",
"Theme parks",
"Ships",
"Arcades",
"Zoos",
"Circuses",
"Carnivals",
"Castles",
"Love hotels",
"Secret bases",
"Military bases",
"Treehouses",
"Being up high",
"Internet cafes",
"Drink shops",
"Delis",
"Supermarkets",
"Flea markets",
"Yard sales",
"Thrift stores",
"High-end stores",
"Bakeries",
"Pet shops",
"Maid cafes",
"Pillow forts",
"Ancient tombs",
"Movie theaters",
"Other people's houses",
"Casinos",
"Train stations",
"Airports",
"Being underground",
"Being at school",
"Going to class",

# misc
"Garbage",
"Herbal medicine",
"Piles of dirt",
"Piles of rubble",
"Destruction",
"Explosions",
"Watching things burn",
"Construction",
"Unhappiness",
"Joy",
"Bacteria and viruses",
"Being upside-down",
"Hide and seek",
"Hiding",
"Seeking",
"Empty plastic wrappers",
"Suffering",
"Disease",
"Vaccines",
"Dirty places",
"Sanitization",
"Neon lights",
"Dead bodies",
"Watching people",
"Sneaking around",
"Blood",
"Shadows",
"Viscera",
"Crime",
"Organs and guts",
"Thinking about death",
"The latest trends",
"Whatever's popular",
"Pop culture",
"Celebrities",
"Movie stars",
"Music stars",
"Popular people",
"Murderers",
"True crime",
"Murders",
"Hurting people",
"Getting hurt",
"Flickering lights",
"Blue lights",
"Red lights",
"Puddles of stagnant water",
"Turning light switches on and off",
"Imagining biting into tinfoil",
"Pushing buttons",
"Pressing buttons",
"Going up and down stairs",
"Circular staircases",
"Responsibilities",
"Seeing faces in things",
"Hearing voices",
"Caring for people",
"Being cared for",
"Following the crowd",
"Static on TVs",
"Advertisements",
"Reviews",
"Awards and medals",
"Sharpening pencils",
"Torii gates",
"Heroics",
"Censorship",
"Censoring",
"Being a hero",
"Electronic components",
"Internet culture",
"Japanese culture",
"Large crowds",
"Night time",
"Daytime",
"The dark",
"Keeping a schedule",
"Being normal",
"Doing laundry",
"Flower language",
"Perfumery",
"Mathematics",
"Philosophy",
"Being hungry",
"Being full",
"Being sleepy",
"Being busy",
"Headpats",
"Touch",
"Strong people",
"Weak people",
"Having free time",
"Headaches",
"Reflections",
"Feeling sick",
"Feeling healthy",
"Empty glasses",
"Feeling strong",
"Being sick",
"Poisons",
"Antidotes",
"Astrology",
"Astronomy",
"Stargazing",
"Stars",
"Magic",
"Religion",
"Full moons",
"The moon cycle",
"Convincing others",
"Living a normal life",
"Being a regular person",
"Being extraordinary",
"Trying your best",
"Feeling comfortable",
"Feeling uncomfortable",
"Midnight",
"The break of dawn",
"Noontime",
"Morning",
"The afternoon",
"Sunset",
"Sunrise",
"Watching the sun set",
"Watching the sun rise",
"Waking up in the morning",
"Getting praised",
"Resisting authority",
"Bragging",
"Decorum",
"Respecting authority",
"The concept of time",
"Getting up in the morning",
"Being annoying",
"Going to bed",
"Following the rules",
"Breaking rules",
"Being early",
"Being late",
"Breaking promises",
"Keeping promises",
"Ancient history",
"Anthropology",
"Cliches",
"Folk sayings",
"Slang terms",
"Profanity",
"Linguistics",
"Folklore",
"Puns",
"Jokes",
"Insulting people",
"Teaching others",
"Sounding smarter than other people",
"The concept of purity",
"Arguing with people",
"Having discussions",
"Participating in debate",
"Being around conflict",
"Being under pressure",
"Taking baths",
"Soaking in hot springs",
"Cold water",
"Cold showers",
"Hot water",
"Hot showers",
"Pills and medicine",
"Vitamins",
"Sounding dumb",
"Being wrong",
"Being right",
"Getting influenced by others",
"Influencing others",
"Personality tests",
"Chewing ice",
"Feeling like you have to sneeze",
"Astrology",
"Psychology",
"Business",
"Medicine",
"Animation",
"Mythology",
"Telling lies",
"Telling the truth",
"Banter",
"War",
"Drugs",
"Gossip",
"Spreading rumors",
"Secrets",
"Problems",
"Other people's business",
"Getting asked for help",
"Helping other people",
"Getting into fights",
"Politics",
"Causing problems",
"Sleeping",
"Obligations",
"Keeping secrets",
"Tactics and strategies",
"Standing out",
"Being the center of attention",
"Not being noticed",
"Causing drama",
"Staying out of drama",
"Flirting",
"Luck",
"Superstition",
"Bad luck",
"Good luck",
"Taking chances",
"Taking risks",
"Taxidermy",
"Figuring stuff out",
"Making new discoveries",
"Changes",
"Changing",
"Transhumanism",
"Cyborgs",
"Intelligence",
"Thinking",
"Being ignored",
"Being photographed",
"Being bullied",
"Tinkering",
"Shipping",
"Making schedules",
"Following a schedule",
"Learning new things",
"Trying new things",
"Being a leader",
"Being a follower",
"Girls",
"Women",
"Boys",
"Men",
"Children",
"Telling jokes",
"Long lines",
"Short lines",
"Straight lines",
"Waiting in line",
"Surprises",
"Working",
"Moving",
"Humor",
"Taking things seriously",
"Taking it easy",
"Working hard",
"Slacking off",
"Weird people",
"Manipulative people",
"Friendly people",
"Talkative people",
"Angry people",
"Gambling",
"Losing",
"Winning",
"Ugly people",
"Looking at people",
"Being around boys",
"Being around girls",
"Working with others",
"Spying",
"Being watched",
"Beautiful people",
"Cute people",
"Talking to people",
"Having a plan",
"Public speaking",
"Intelligent people",
"Dumb people",
"Love",
"Friendship",
"Pain",
"Feeling numb",
"Complaining",
"Caring about other people",
"Making sacrifices",
"Criticism",
"Compliments",
"Being thanked",
"Being teased",
"Nothing",
"Everything",
"Teasing",
"Wasting time",
"Doing nothing",
"Loose ends",
"Mysteries",
"Unexplained things",
"Feeling trapped",
"Tight spaces",
"Games of chance",
"Games of skill",
"Doing research",
"Creating new things",
"Being the best",
"Challenges",
"Taking bets",
"The paranormal",
"Ghosts",
"Monsters",
"Dinosaurs",
"Good manners",
"Working under pressure",
"Emergencies",
"Cowboys",
"Superheroes",
"Justice",
"Ninjas",
"Royalty",
"Bones",
"Fossils",
"Taxidermy",
"Preservation",
"Pickling",

]
